### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by wilsonk** [TheLordYugi/SharpSquish#1]
Hello Eduardo,

Just wondering what license your code is released under? There doesn't seem to be a license file so, according to the github terms of service:
 
"Generally speaking, the absence of a license means that the default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work. This might not be what you intend."

If this was what you intended, then I thank you for the opportunity to view your code, but I was hoping to possibly use it in another open source project (MIT or Apache). Is there a chance that a compatible license could be attributed to your project?

Thanks,
Kelly

**Comment by TheLordYugi** [comment]
Hello Kelly, Sorry for the very long time. I have some problems and go back now.
I'm change the Licence for MIT. Sorry for the long wait time, and sorry for my very bad english.

**Comment by wilsonk** [comment]
Hello Eduardo,

Thanks for the reply and the change of the license to MIT. I will look back at my old project and see whether I can still use your code. Much appreciated. Don't worry about the English, you expressed yourself just fine :)

**Comment by TheLordYugi** [comment]
Thanks for the reply. :)
